services:
  mongodb:
    image: mongo:8.0
    container_name: hp_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./hp-backend
    container_name: hp_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    volumes:
      - ./hp-backend/data:/app/data
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./hp-frontend
    container_name: hp_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
