import re, os
from pathlib import Path
OUT=Path('/Users/yogeshyadav/Desktop/HP/project-documentation')
Q=[]
def q(**k):
    k.setdefault('unclear',''); k.setdefault('why',''); k.setdefault('need',''); k.setdefault('sixfile',None); Q.append(k)

# ---- opens_1 (10 data questions, sent 23 Sep 18:56 UTC, answered 24 Sep) + opens_2 (43 items sent 24 Sep 07:35 UTC, answered 24 Sep 14:43 UTC) + round 3 (25 Sep) ----
q(id='D1', title='Canonical account list with one domain each', feature='Identity / every join',
  asked='220-Open-Decisions-List item 1 (24 Sep). 220 Explorium workbooks resolve to 217 unique domains; identity blank on 209 of 219 rows. Default offered: the domains in _RUN_SUMMARY.',
  answer='"OPEN: WILL GIVE THAT" (clarifying opens_2, 24 Sep). Round 3 A1 re-asks: "Please send the master list of 220 accounts with one domain each."',
  date='2026-09-24', status='OPEN', resolves='No — a delivery was promised, nothing received.',
  impact='Every join, the split, every per-account run. Three accounts appeared to have no intent data until alias domains were applied.',
  unclear='Which domain is authoritative for the ~4 accounts where vendors differ and the 2 with blank domains; whether a stable account id can be added.',
  why='Wrong domain = one company\'s data on another company\'s page, or silently empty widgets.', need='The master list of 220 accounts with one domain each (or a stable account id on every file).', sixfile='01_canonical_account_list')
q(id='D2', title='Entity scope: APAC entity or global parent', feature='Firmographics, hierarchy, Executive Dashboard',
  asked='Item 2. Vendor logged 141 field conflicts and kept the global HQ value each time (Jabil = Waltham MA, not Shatin HK). Default: APAC entity as named; firmographics as delivered.',
  answer='"->RESOLVED" with no further words.', date='2026-09-24', status='PARTIALLY RESOLVED',
  resolves='Partly — a bare "RESOLVED" against a question that offered a default; taken as default accepted. Round 3 CLARIFICATIONS_v2 A2 asks for explicit confirmation.',
  impact='Executive Dashboard header, firmographics, hierarchy for ~141 conflicted fields.',
  unclear='Whether "RESOLVED" means "use the default" or "the conflicts are fine as delivered".', why='Sellers of the APAC entity would see the US HQ address and headcount.', need='One line: "APAC entity values" or "as delivered".', sixfile='02_entity_scope_resolved_ambiguously')
q(id='D3', title='Shared domains jabil.com and mufg.jp: which entity owns the rows', feature='Hiring, tech detections, news, connections for 4 accounts',
  asked='Data question 2 (23 Sep) and item 3. Can vendors supply a per-entity id? Treat the pairs as one account? Which entity owns the rows?',
  answer='opens_1 answer 2: id "not possible currently"; one account each "no"; "Please take Company Name + Country into consideration along with the domain … Open: We will provide additional columns Company Name + Country in the mentioned sheets." opens_2 item 3: "ALREADY RESOLVED IN CLARIFYING_OPENS_1 DOC".',
  date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Rule yes, data no. Round 3 A3: the columns exist but are populated on 384 of 14,965 job rows, only for the secondary entities.',
  impact='Jabil Malaysia / Singapore and MUFG Japan / Bangkok branch cannot be separated in hiring, technology, news, connections.',
  unclear='Nothing about the rule; the data that makes the rule executable has not arrived.', why='Until the columns are populated on every row the interim split gives Jabil SG and the Bangkok branch almost no data.', need='input_company_name and input_country_code populated on every row of job_openings, technology_detections, news_events, connections, subpages and sec_filings.', sixfile='03_shared_domains_name_country_columns')
q(id='D4', title='Blank domains: Public Bank and Westpac', feature='All datasets for two accounts',
  asked='Data question 3 and item 4. Confirm publicbankgroup.com and westpac.com.au (we were deriving them).',
  answer='opens_1 answer 3: "pls look at below two domains: pbebank.com, westpac.com.au"; "Please populate Company Domain in the next delivery -> noted".',
  date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Westpac yes. Public Bank no — see D6; the two answers pull against each other (round 3 UNRESOLVED A4).',
  impact='Public Bank: all PredictLeads data held; the 25 Sep split nevertheless derived publicbankgroup.com (internal conflict I-02).',
  unclear='Whether pbebank.com is the key for Explorium / Exa / Google News for this account while the PredictLeads rows under it belong to the Lao subsidiary.', why='Adopting pbebank.com today puts the Lao subsidiary\'s hiring and technology on the Malaysian parent\'s page; name+country fallback cannot rescue it because both fields are blank on that row.', need='Public Bank Berhad (Malaysia) rows for PredictLeads, and confirmation of pbebank.com as the key for the other sources.', sixfile='04_public_bank_domain_and_pbebank_rows')
q(id='D5', title='Vendor domain mismatches (Posco, Pilipinas Shell, Shiseido, Stanley Electric)', feature='Hiring, news, tech detections for 4 accounts',
  asked='Data question 4 and item 5. Confirm the four aliases; is there a stable id?',
  answer='opens_1 answer 4: canonical domains are the PredictLeads ones; four overrides: Posco Group → posco.com, Pilipinas Shell → shell.com.ph, Shiseido → corp.shiseido.com, Stanley Electric → stanley.co.jp; vendors are fetched by Company Name + Country, so differing domains do not mean a wrong company; "where domain matching is ambiguous, use Company Name + Country as the fallback".',
  date='2026-09-24', status='RESOLVED', resolves='Yes. Note the split rewrites two aliases toward the Explorium domains (internal conflict I-03) — engineering must align with the client direction.',
  impact='Domain joins for those accounts; the alias table.')
q(id='D6', title='pbebank.com: Public Bank Bhd or Public Bank Lao?', feature='One account',
  asked='Data question 5 and item 6.', answer='opens_1 answer 5: "open: We will try and give you exact name \'public bank bhd\' data for predictleads_combined_219_accounts.xlsx … Public Bank Lao Limited is a wholly-owned subsidiary of Public Bank Berhad, which is why the same domain is associated with both entities."',
  date='2026-09-24', status='UNRESOLVED', resolves='No — see D4; corrected rows promised.', impact='Public Bank PredictLeads data withheld.', sixfile='04_public_bank_domain_and_pbebank_rows')
q(id='D7', title='Hierarchy: 55 accounts without a sheet; blank parent', feature='Executive Dashboard, firmographics',
  asked='23 Sep question 1 (PT Astra lists itself as its own parent) and item 7 (show "no hierarchy data" or leave the section out?).',
  answer='23 Sep: "If a Parent Name is provided there, we should use that parent relationship. If the Parent Name is blank, the parent relationship can be ignored for now." opens_2 item 7: "Resolved: nothing to mention, do not write \'no hierarchy data\'."',
  date='2026-09-23', status='RESOLVED', resolves='Yes.', impact='Hierarchy widget; the only client rule on empty states so far (say nothing).')
q(id='D8', title='Contact file for the 220 accounts', feature='Stakeholder Map, Opportunity Map, Objection Playbook, Content Studio, Message Evaluator (BLOCKER)',
  asked='Data question 1 (23 Sep), item 8, 24 Sep email §3, round 3 B2. Contacts sheet empty in all 220 workbooks; Apollo_All_Contacts named in v4 not received.',
  answer='opens_1: "Ans 1) Contact Data open". opens_2 section B: "->OPEN". Per round 3 B2 the client has since said contacts cannot be fetched for every account: some accounts get names and details, the rest names or roles only, with prompts and supporting material to follow.',
  date='2026-09-24', status='OPEN', resolves='No.', impact='None of the five features can be generated for any account; once the file lands all five must be built and re-tested.',
  unclear='When it arrives, keyed on what, which accounts get real contacts vs names/roles only, and what the "prompts and supporting material" are for.', why='Five of eleven features cannot run.', need='The contact data keyed on domain + company name + country, a per-account coverage note, and the prompts/material with the feature each is for.', sixfile='05_contact_file_missing')
q(id='D9', title='Role coverage: ~30 buying-committee roles, then 5-8 more', feature='Contacts',
  asked='Item 9 and round 3 B3.', answer='No answer (section B marked OPEN).', date='2026-09-24', status='OPEN', resolves='No.', impact='Whether the five contact features are built once or twice.',
  unclear='One file or two.', why='A second round means regenerating five features again.', need='Confirmation: one file or two, and when.', sixfile='05_contact_file_missing')
q(id='D10', title='Stakeholder Map with zero contacts: message or hidden', feature='UI for every account until contacts arrive',
  asked='Item 10 and round 3 B4. Default: show the empty state with a message.', answer='No answer (section B OPEN).', date='2026-09-24', status='OPEN', resolves='No.', impact='Stakeholder Map on all 220 accounts today.',
  unclear='Whether the hierarchy rule (say nothing) generalises.', why='Sellers will read a missing section as a bug.', need='One choice: show with message, or leave out.', sixfile='06_empty_state_behaviour')
q(id='D11', title='Which filings source is authoritative; count; accounts without filings', feature='Executive Dashboard financials/priorities, Strategy Chat, Opportunity Map, Content Messaging, Live Signals',
  asked='18 Sep question 3, data question 10, item 11, round 3 C1/C5. 184 vs 186 vs 192 counts; document_url vs local_path; two NZ accounts linked to Malaysian parents.',
  answer='18 Sep: "Please use document_url where available and source_page_url as the fallback. Do not use local_path. Where both source URLs are blank, please exclude that record." opens_2 item 11: "RESOLVED: use filings 1.csv plus PredictLeads SEC Filings, merged on domain but where the domain is same … pls use company name and country … and yes pls consider \'the file shows 186 unique company names\'" + list of 31 accounts with no public filings. opens_1 answer 10: "Sec filings: pls use from filings.csv + predictleads data->sec_filings".',
  date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Method yes. Reconciliation no: 31 excluded + 187 covered = 218, so Agribank and VPBank are on neither list (round 3 C1); Jabil Inc. 10-Q rows keyed SG and MY and Hyundai DART rows cannot be placed (round 3 C5); VPBank documents sit under "VIETNAM POST CORPORATION".',
  impact='Financial figures and strategic priorities on the Executive Dashboard for those accounts.', unclear='Whether Agribank/VPBank have filings; whether parent (Jabil Inc.) filings attach to both APAC entities; whose reports the DART rows are.', why='Filings feed five features; one company\'s filings must not appear on another\'s page.', need='Yes/no on Agribank and VPBank; yes/no on Jabil (both/neither); Hyundai Autoever vs Hyundai Motor for the DART rows; re-key VPBank out of Vietnam Post.', sixfile='07_filings_reconciliation')
q(id='D12', title='Filing documents, not just links', feature='Executive Dashboard, ingestion time', asked='Item 12. Are the URLs downloadable or will files be provided?',
  answer='"RESOLVED: you can verify it with https://drive.google.com/drive/folders/1FAMRDkL7Y0E8LSzEYu7FmmVA0VVAgCgP … wherever it is not downloaded, or links fail: we skip that particular file, not the whole company".', date='2026-09-24', status='RESOLVED', resolves='Yes as a rule; the Drive folder is not reachable from this machine (see MISSING_FILES.md C38).', impact='compliance_filings ingestion.')
q(id='D13', title='Filings window', feature='Executive Dashboard', asked='Item 13. Confirm 12 months.', answer='"resolved: last 12 months"', date='2026-09-24', status='RESOLVED', resolves='Yes.', impact='Older filings dropped at ingestion.')
q(id='D14', title='Three accounts with a wrong filings mapping', feature='Filings', asked='18 Sep question 3 and item 14; names sent in round 3 C4: Fletcher Building (rows carry sunway.com.my), Fonterra (uob.com.my), Astra (fifgroup.co.id; plus a blank-domain row holding United Tractors statements).',
  answer='opens_2: "open: pls send, noted!" — names sent 25 Sep; no correction received.', date='2026-09-24', status='OPEN', resolves='No.', impact='Those rows are excluded until corrected; Federal International Finance has no filings of its own.',
  unclear='Nothing; awaiting corrected rows.', why='Domain tie-break can misfire and attribute one company\'s filings to another.', need='Corrected domain and global_parent values for the 10 rows; FIF filings if any; remove or relabel the United Tractors row.', sixfile='07_filings_reconciliation')
q(id='D15', title='Stock Exchange data of 3 Sep superseded?', feature='Filings', asked='Item 15.', answer='"already resolved: she shared with you different pdfs"', date='2026-09-24', status='RESOLVED', resolves='Yes (filings 1.csv + PDFs replace it).', impact='None.')
q(id='D16', title='News precedence when Exa and Google News RSS disagree', feature='Live Signals',
  asked='Data question 6, item 16, round 3 D1. Exa replacement or supplement? Merge? Which wins?',
  answer='opens_1 answer 6: "no it is not a replacement … merging both … in the rare case that this happens, please skip that particular news item. Do not skip the company directly." opens_2 item 16: "->open" and forwarded to Sahaj on 24 Sep 14:43 UTC.',
  date='2026-09-24', status='PARTIALLY RESOLVED', resolves='The skip rule is written; the client then re-marked the item open, and the "same event" definition (same account + same date + normalised headline; 356 duplicates removed) is ours and unconfirmed.',
  impact='Which rows appear in Live Signals; 356 rows already removed as duplicates.', unclear='Whether answer 6 stands (skip) or Sahaj prefers Exa-first with RSS as supporting reference; whether our same-event definition is accepted.', why='Determines feed content for every account with both sources.', need='Confirm answer 6 stands, and a yes/no on the same-event definition.', sixfile='08_news_precedence_and_same_event')
q(id='D17', title='Undated Exa rows (5,120 of 9,221) and three 1970-01-01 rows', feature='Live Signals, urgency, every time-based signal',
  asked='Data question 7, item 17, round 3 D2.', answer='opens_1 answer 7: "We will provide the date wherever possible by crawling the URLs. For any rows where the date will still not available, please skip that news row for now, do not skip whole company/account"; epoch rows: "skip these three news items as of now".',
  date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Rule yes; re-crawl not received. Exa is the only source for ~119 accounts, so they lose over half their news until then.', impact='Live Signals volume; AI/growth events in the urgency score.',
  unclear='Nothing; awaiting the re-export and its recovery count.', why='Without dates most Exa rows are dropped under the skip rule.', need='Re-exported Exa file with ISO dates and a count of how many of the 5,120 received a date.', sixfile='09_exa_event_dates')
q(id='D18', title='Exa as its own dataset key and on-screen label', feature='Source labels on news cards',
  asked='Item 18 and round 3 UNRESOLVED D3. Add a dedicated Exa key, or accept the "Google News" label?', answer='"Resolved: pls use domain + company name + country" — answers matching, not labelling.',
  date='2026-09-24', status='UNRESOLVED', resolves='No — the answer addresses a different question.', impact='Every news card sourced from Exa (215 accounts) is labelled Google News today.',
  unclear='Whether a card should say "Exa", "Google News", or the publisher name only.', why='Mislabelled provenance on most news cards.', need='One of: "Exa" by name / "Google News" for both / publisher name only. (We are adding an exa key regardless.)', sixfile='10_exa_source_label')
q(id='D19', title='12-month news window and 20-signal cap', feature='Live Signals volume', asked='Item 19. Keep both?', answer='"Resolved: we should not keep the cap, pls use 12 month window"', date='2026-09-24', status='RESOLVED', resolves='Yes — default overturned: no cap.', impact='All scored signals in the window are shown; HP-Input-Data-Contract.md still documents the cap (stale).')
q(id='D20', title='Low-confidence news rows', feature='Live Signals ranking', asked='Item 20. Exclude Low, down-weight, or leave?', answer='"Already Resolved: mentioned in yesterday\'s meeting, pls do not use low/high confidence columns from those feeds"', date='2026-09-24', status='RESOLVED', resolves='Yes.', impact='relevance_confidence column ignored.')
q(id='D21', title='Corrupted Thai text and raw HTML in Exa', feature='News cards', asked='Data question 9 and item 21.', answer='opens_1 answer 9: "This is the data which we get from tool itself"; "If you could help strip it on ingest, it would be appreciated".', date='2026-09-24', status='RESOLVED', resolves='Yes (HTML stripped by us; corrupted cells shown as delivered).', impact='28 cells for Thai accounts.')
q(id='D22', title='Coverage gaps: intent 173/220, jobs 175/220, technographics 207/220', feature='Intent & Demand, hiring, Technographic Map, urgency',
  asked='Data question 10, item 22, round 3 E1.', answer='opens_1 answer 10: "no data cases … Job Openings: … we will aggregate it from other tools and give you in same format … Technographics: Please look at the WebStack and Tech_Breakdown sheets … fallback … Related Technologies column".',
  date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Rule yes; the job rows for the 45 accounts have not arrived; and "Related Technologies" is researched, not detected, technology — round 3 E1 asks for one line confirming it is shown as such.',
  impact='45 accounts have no hiring widgets and no hiring driver in the Urgency Score.', unclear='When the job rows arrive and from which tool (source reliability differs); whether Related Technologies may be shown as detected technology.', why='Hiring feeds two widgets and 30% of the urgency weight.', need='Job rows for the 45 accounts in the job_openings layout (name + country on every row, posted date, status, tool name) and one line on Related Technologies.', sixfile='11_job_openings_45_accounts_and_related_technologies')
q(id='D23', title='219 vs 220: which account is absent from PredictLeads', feature='PredictLeads', asked='Item 23.', answer='"Astra: already provided initially … ALREADY RESOLVED IN CLARIFYING_OPENS_1 DOC"', date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Mostly; round 3 CLARIFICATIONS_v2 E2 asks whether the 31 Aug seed extract is the same format and version as the 219-account file.', impact='Astra hiring/tech/news come from the seed.', sixfile='12_astra_seed_extract_version')
q(id='D24', title='Duplicate record ids inside PredictLeads', feature='Technology counts, news counts', asked='Data question 8 and item 24. De-dup on id, first row kept?', answer='opens_1 answer 8: "Why are we using IDs? We should use Domain + Company name for mapping." opens_2: "Why are we using ids, already mentioned that pls use domain, company name and country".', date='2026-09-24', status='RESOLVED', resolves='Yes as an instruction (do not key on ids); round 3 E3 records duplicates as cleared.', impact='De-duplication keyed on domain + name + country + content, not vendor id.')
q(id='D25', title='Vendor-flagged doubtful rows (9)', feature='Hiring and technographic signals', asked='Item 25 and round 3 E4: 4 job postings attributed to the wrong employer, 1 MISO misreading, 4 duplicate company profiles. Drop them?', answer='"clarifications needed"', date='2026-09-24', status='OPEN', resolves='No.', impact='9 rows.', unclear='Whether to drop or load as delivered.', why='Wrong-employer postings become false hiring signals.', need='One line: drop the 9 rows (default if silent) or keep.', sixfile='13_vendor_flagged_rows')
q(id='D26', title='490 logged corrections: applied or to-do?', feature='Hiring and tech dates', asked='Item 26 and round 3 E5.', answer='"clarifications needed"; cleared by our own inspection: 332 corrected values present, none old — the delivered file is post-correction.', date='2026-09-24', status='RESOLVED', resolves='Yes, by inspection (internal finding stated to the client).', impact='None; the log is not re-applied.')
q(id='D27', title='Job status: label wording and whether blank means open', feature='exec_hiring_velocity, intent_hiring_demand, urgency driver 3', asked='Input-contract 5.1 (16 Sep), item 27, round 3 E6. Blank and closed count for urgency (confirmed 16 Sep); label hiring widgets "postings seen" with the open count beside it?', answer='16 Sep: "please include both blank and closed job statuses for eligible records within the latest 12 months." opens_2 item 27: "clarifications needed".', date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Scoring rule yes; label wording and the meaning of a blank status no.', impact='Label only for the widgets; the Hiring driver may be overstated if blank means unknown.', unclear='Does a blank status mean open or unknown; preferred label wording.', why='In the Astra seed 60 postings are closed, 40 blank, none open.', need='(a) blank = open or unknown; (b) approve "postings seen" + open count, or give wording.', sixfile='14_job_status_label')
q(id='D28', title='Twelve PredictLeads keys with no consumer', feature='Upload contract', asked='Item 28. Products for recommendations only; remove the rest?', answer='"Resolved: yes" (and 23 Sep: use sec_filings and products, ignore the others).', date='2026-09-24', status='RESOLVED', resolves='Yes. The feature list for the Products sheet is only in a 23 Sep screenshot not on this machine.', impact='Upload contract; recommendations.')
q(id='D29', title='Relevance threshold for Rulebook offerings and case studies', feature='Every recommendation', asked='21 Sep (email), 24 Sep email §5.1, item 29, round 3 F1. Exact/alias match only, or category-level match too?',
  answer='Dhruvi 24 Sep 09:30 UTC: use-case/opportunity fit; "relevant" when clearly supported, "may be relevant / explore fit" when conditional; a technology or integration-route match alone is not sufficient (BHP Intune/ServiceNow example); case studies support an established opportunity, they do not create it. opens_2 item 29: "Already resolved: Explained in the email".',
  date='2026-09-24', status='PARTIALLY RESOLVED', resolves='The rule is stated. Round 3 F1 asks for a one-line restatement and describes the build as "exact or known-alias matches only" — the build and the rule differ (CONFLICT X-09). Sub-items 29a-c not yet answered.', impact='Every recommendation across all features.', unclear='Nothing in the rule; the open point is confirming the build matches it, plus 29a (integration route as a context line), 29b (unevaluable conditions treated as unmet), 29c (use-case vocabulary table).', why='Changes the final output of every feature.', need='Confirmation of 29a/29b defaults and approval of the 29c table when sent.', sixfile='15_relevance_rule_implementation')
q(id='D30', title='Where the Rulebook and case studies appear', feature='All features', asked='21 Sep email, item 30.', answer='"resolved: pls include stakeholder map as well"; 24 Sep annotation: already resolved by the 18 Sep mapping file.', date='2026-09-24', status='RESOLVED', resolves='Yes: as built (Objection Playbook, Opportunity Map, Content Messaging, Content Studio, Strategy Chat, plus recommendation text in Executive Dashboard, Live Signals, Intent & Demand, Technographic Map) plus Stakeholder Map. Follow-ups F8-F13 have stated defaults.', impact='Proof-point placement.')
q(id='D31', title='89 cleaned case studies as the corpus', feature='Proof library', asked='Item 31.', answer='"resolved: yes"', date='2026-09-24', status='RESOLVED', resolves='Yes.', impact='hp_case_studies_final.csv 384 rows → 89 distinct studies; corrupted figures never shown.')
q(id='D32', title='"Recommendation for HP" on every Technographic Map section', feature='Technographic Map', asked='24 Sep email §5.3, item 32.', answer='"RESOLVED : DROP IT for now"', date='2026-09-24', status='RESOLVED', resolves='Yes.', impact='Card stays limited to the two categories it maps today (or is dropped).')
q(id='D33', title='3D printing route without Rulebook rules', feature='Recommendations', asked='Item 33. Default: 3D intent scored but no product recommendation until rules exist.', answer='"the absence of a matching 3D or Workstation rule in the Rulebook should not block an otherwise supported recommendation … Not every recommendation is expected to have a matching Rulebook entry or case study."', date='2026-09-24', status='RESOLVED', resolves='Yes — default overturned; evidence-led.', impact='3D and Workstation routes generate recommendations at the supported-opportunity level.')
q(id='D34', title='One recommendation or five routes', feature='Opportunity Map ordering', asked='Item 34 and round 3 F4.', answer='"clarification needed, which five routes?" — round 3 F4 names them (3D Printing, Workstations, PC/Devices, Print, Poly, slide 5 of the 15 Sep deck) and states the build: strongest route as the recommendation, weaker ones as secondary hypotheses, per slide 3.', date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Cleared on our side; silence default; not confirmed.', impact='Opportunity Map ordering.', unclear='Whether the client agrees with the slide-3 reading.', why='Changes how many recommendations a seller sees.', need='"Agree" or an alternative.', sixfile='16_one_primary_recommendation')
q(id='D35', title='Confidence tiers T0-T3', feature='Every signal; case-study file', asked='Item 35 and round 3 F5. What does each tier mean; is the case-study T0/T2 the same scale?', answer='"clarification needed, which feature?"', date='2026-09-24', status='OPEN', resolves='No.', impact='confidence_tier field required by v4 on every signal; build maps to High/Medium/Low.', unclear='Definition of the four tiers and whether case-study source_tier uses the same scale.', why='v4 requires the field; wrong mapping mislabels every signal.', need='Tier definitions, or confirmation that High/Medium/Low is acceptable.', sixfile='17_confidence_tiers_T0_T3')
q(id='D36', title='Live Signal S/A/B/C tiers and minimum publish score', feature='Live Signals', asked='18 Sep question 4 and item 36.', answer='18 Sep: "I don\'t see the S/A/B/C tiering defined in the HP SEA limited poc … Could you please confirm where the current S/A/B/C classification in the UI is coming from"; opens_2: "Resolved: use live signal scoring logic as given as I can see in sea limited, there is a score instead of tiers".', date='2026-09-24', status='RESOLVED', resolves='Yes — no tiers, no minimum; score /10 shown.', impact='news_signals_feed; HP-Account-Intelligence-Rules.docx section is stale.')
q(id='D37', title='Technographic Map Low/Medium/High risk logic', feature='Technographic Map', asked='23 Sep (Dhruvi asked us); item 37; logic sent 23 Sep as a screenshot and in words in round 3 F7.', answer='23 Sep: "Please retain the Low Risk / Medium Risk / High Risk labels … what logic is currently being used"; opens_2: "open" and forwarded to Sahaj 24 Sep 14:43 UTC ("whether the risk logic is good to go from your end").', date='2026-09-24', status='OPEN', resolves='Labels yes; approval of the logic no.', impact='technographic_map risk column.', unclear='Whether Sahaj accepts the lookup (High = competing vendor confirmed; Medium = need supported, no vendor; Low = HP can work alongside; no label where HP has no line; HP-absence row always Medium).', why='Labels are shown today on the client\'s own logic request.', need='"Good to go", rename to Competitive position (Incumbent / Open / Complementary), or drop.', sixfile='18_tech_map_risk_labels')
q(id='D38', title='Service rules that need inputs the data lacks (seat count, WXP tier, print volumes, lifecycle dates)', feature='Care Pack / WXP / Poly / Print rules; lifecycle check', asked='Item 38 and round 3 F6.', answer='"resolved/clarification needed: pls ignore that pending HP input, and use whose data we fully have, no as of now we might not ask seller to enter seats, so hold employee range. lifecycle date, which columns to look into? -> clarifications needed"', date='2026-09-24', status='PARTIALLY RESOLVED', resolves='Pending items skipped and employee range used — yes. The specific employee-range thresholds (501 / 1,001 / 5,001) are ours and unconfirmed; which Lifecycle column (PE vs EM, duplicated PE heading, stacked dates in one cell) is unanswered; the readable Lifecycle file is not on this machine.', impact='Which service rules fire; lifecycle gate in v4 §J.', unclear='Threshold approval; lifecycle column semantics; whether Lifecycle is in use at all (client file explanation says "Not used").', why='Rules silently never fire or fire on a wrong proxy.', need='(a) yes to the employee-range thresholds or alternatives; (b) which Lifecycle column and what stacked dates mean; (c) an unencrypted Lifecycle copy.', sixfile='19_seat_proxy_and_lifecycle_columns')
q(id='D39', title='Empty-state behaviour for any missing dataset', feature='Every widget', asked='Item 39, round 3 G1. Show with a "no data from source" message or hide?', answer='"-> open" (forwarded to Sahaj).', date='2026-09-24', status='OPEN', resolves='No.', impact='Contacts (all accounts), hiring (45 accounts), filings (31 accounts).', unclear='Show or hide.', why='Absence read as a bug vs silent omission; two internal docs propose opposite defaults (CONFLICT I-01).', need='One choice, applied also to B4.', sixfile='06_empty_state_behaviour')
q(id='D40', title='Source label set on screen', feature='Every source chip', asked='Item 40, round 3 G2. Approve Firmographics, Technographics, Hiring, News, Filings, Intent, HP Rulebook, HP case study; publisher name on news cards; no vendor names.', answer='"-> open" (forwarded to Sahaj).', date='2026-09-24', status='OPEN', resolves='No.', impact='UI labels everywhere.', unclear='Approval of the set; Exa label (D18).', why='Raw file names on screen "create a negative impression" (23 Sep call).', need='Approve the label set or amend it.', sixfile='20_source_labels')
q(id='D41', title='Data as-of date', feature='As-of line on every screen; recency anchor', asked='Item 41, round 3 G3. Date of the 23 Sep drop or of the final consolidated drop?', answer='"-> open"', date='2026-09-24', status='OPEN', resolves='No.', impact='Every screen; recency calculations (CONFLICT C-02).', unclear='Which date.', why='v4 requires one shared data_as_of_date per snapshot.', need='Confirm: final consolidated drop, shown once per account.', sixfile='21_data_as_of_date')
q(id='D42', title='GCP access, project id, region', feature='Environment', asked='15 Sep action item; 24 Sep email §4; item 42; round 3 H1; access request doc sent 23 Sep via WhatsApp.', answer='"-> open"; "RESOLVED: Already followed up with sahaj" (on the follow-up action only).', date='2026-09-24', status='OPEN', resolves='No.', impact='The current environment cannot hold 220 accounts; a few hours of redeploy/load once granted.', unclear='Project id, region, when.', why='Blocks the 220-account run.', need='Access, project id, region.', sixfile='22_gcp_access')
q(id='D43', title='Inspection window for late-night drops', feature='Process', asked='Item 43.', answer='"resolved: yes"', date='2026-09-24', status='RESOLVED', resolves='Yes.', impact='Delivery planning.')
# items 44-53 added 24 Sep after the list went out (round 3 F8-F13, I1, I2, F1a-c)
for i,(t,f,asked,default) in enumerate([
 ('Proof method for the four features with no v4 row (Objection Playbook, Content Studio, Strategy Chat, Message Evaluator)','Proof placement','Round 3 F8 (item 44).','As built: one case study per area card; a Proof Points section per asset; citations of attached proof; Rulebook facts only.'),
 ('Case-study proof on the signal features (Live Signals, Intent & Demand, Stakeholder Map, Technographic Map): now or after?','Proof placement','Round 3 F9 (item 45).','After, on the same matcher.'),
 ('Proof on service plays in the Opportunity Map','Opportunity Map','Round 3 F10 (item 46).','Yes.'),
 ('Evidence-tier gate on proof (only once an Opportunity is established by two pipelines)','Proof placement','Round 3 F11 (item 47).','Apply it.'),
 ('APJ region preference as the second sort key for proof','Proof ranking','Round 3 F12 (item 48).','Yes.'),
 ('Product-line mapping for case studies: keyword table now, Rulebook offering ids after','Proof matching','Round 3 F13 (item 50).','Yes.'),
 ('Integration route detected on its own shown as a context line?','Recommendations','Round 3 F1a (item 29a).','Shown as a context line, never inside the recommendation.'),
 ('Conditions the data cannot evaluate treated as unmet (offering reaches "may be relevant" but never "relevant")','Recommendations','Round 3 F1b (item 29b).','Yes.'),
 ('Use-case vocabulary table (Rulebook opportunity type → case-study solution area/tags) — we write it','Case studies','Round 3 F1c (item 29c).','Our table applies until changed.'),
 ('A realistic delivery date starting from the day data and GCP access are in hand','Process','24 Sep email §7.4; round 3 I1.','—'),
 ('Remaining deliveries as one consolidated drop with a contents list','Process','24 Sep email §3; round 3 I2.','—')]):
    q(id=f'D{44+i}' if i<6 else (['D29a','D29b','D29c','D51','D53'][i-6]), title=t, feature=f, asked=asked+' Not in the version the client answered.', answer='Not yet put to the client / not answered.', date='2026-09-25', status='OPEN', resolves='No.', impact=f, unclear='—', why='Stated default applies if silent.', need=f'Yes/no. Default: {default}')
q(id='D52', title='JEV (decision model) inside this delivery?', feature='Scope', asked='24 Sep email §5.4.', answer='"RESOLVED : DROP IT for now"', date='2026-09-24', status='RESOLVED', resolves='Yes.', impact='Out of this delivery.')
# 18 Sep and 23 Sep Q&A not otherwise covered
q(id='E18-1', title='Unencrypted copies of Lifecycle / Wolf / HP IQ', feature='Reference', asked='18 Sep question 1.', answer='18 Sep 07:28 UTC: "PFA the files" — Hp lifecycle june 2026.xlsx, Wolf_Security_Portfolio_Recreated.pptx, HP_IQ_for_Enterprise_Recreated.pptx.', date='2026-09-18', status='RESOLVED', resolves='Yes by the client; the three files never reached this machine (MISSING_FILES.md).', impact='Reference only (content folded into the Rulebook).')
q(id='E18-2', title='Lifecycle/EOL for Fleet Refresh?', feature='Urgency', asked='18 Sep question 2.', answer='"Fleet Refresh should remain excluded for now … we don\'t have data showing which HP device models each account currently uses."', date='2026-09-18', status='RESOLVED', resolves='Yes.', impact='Urgency has no Fleet Refresh driver.')
q(id='E23-2', title='Opportunity Map three checks (Verified Evidence / Timing Trigger / HP Fit)', feature='Opportunity Map', asked='23 Sep question 2.', answer='"we can drop these for now. Please retain only the Priority tags -Critical, High, Medium, Low as seen in sea limited".', date='2026-09-23', status='RESOLVED', resolves='For the UI yes; what computes the Priority label is not stated by the client (CONFLICT C-09).', impact='opportunity_narrative_plays tags.')
q(id='E23-3', title='"Contextual — no direct HP line" relationship tag', feature='Technographic Map', asked='23 Sep question 3 (with the risk labels).', answer='Only the risk-label half was answered.', date='2026-09-23', status='OPEN', resolves='No (by omission).', impact='Rows with no HP category.', unclear='Keep or drop the tag.', why='Not in any client document.', need='One word.', sixfile='18_tech_map_risk_labels')
q(id='E23-4', title='Which new PredictLeads sheets to use', feature='Upload contract', asked='23 Sep question 4.', answer='"please use the SEC Filings data … Please also use the Products sheet (mainly for recommendation purposes) for the following features: [screenshot]. You can ignore others".', date='2026-09-23', status='PARTIALLY RESOLVED', resolves='Yes, except the feature list for Products exists only in a screenshot not on this machine.', impact='Products consumption.', unclear='Which features consume the Products sheet.', why='Cannot verify the build against the instruction.', need='The list in text (or the screenshot).', sixfile='23_products_sheet_feature_list')
# 16 Sep QA discussion points (12) — no client answer on record
for i,(t,f) in enumerate([('Objection Playbook wording "Could be raised by" vs QA check "Likely raised by" (OP-03/OP-07)','Objection Playbook'),('"Counter Question" box reported missing (OP-06) — rendered in capitals','Objection Playbook'),('Opportunity Map HP-modeled / unsourced labels (OM-10/OM-13) — feature never emits unsourced numbers','Opportunity Map'),('Content Messaging unsourced proof points labelled "HP analysis" (CM-15) — we delete instead','Content Messaging'),('Tech Landscape confidence percentage (TM-11) vs Confirmed/Likely/Unknown words','Tech Landscape'),('Stakeholder avatar: initials vs photo (SM-10)','Stakeholder Map'),('LinkedIn 999 / Apollo URN / Google redirect links reported broken','Stakeholder Map, Live Signals'),('Active-employee label (SM-07/SM-26) — no employment-status column exists','Stakeholder Map'),('Strategy Chat source links / uncertainty state stay open until Step 8 RAG','Strategy Chat'),('Cost/scheduling of regenerating cached content after prompt changes','All'),('~200 technologies that map to no HP category: separate view or count only?','Tech Landscape'),('Repeated "Step 4" data suggestions (xlsx, PDFs, car-market data) are new features, not fixes','All')]):
    q(id=f'QA16-{i+1}', title=t, feature=f, asked='QA-Discussion-Points_2026-09-16 (sent 16 Sep 19:14 UTC as PDF), asking for a classification/decision per item.', answer='No written answer on record. TM-11 is overtaken by the client\'s 18 Sep confidence logic (a percentage now has a client basis); the Opportunity Map tags question was overtaken on 23 Sep.', date='2026-09-16', status='OPEN', resolves='No.', impact=f, unclear='Whether the validator checks are to be changed or the product.', why='Some checks would make the product less honest if passed literally (see objection wording).', need='A per-item decision.', sixfile='24_qa_discussion_points_unanswered' if i==0 else None)
q(id='RULES', title='Client feedback on HP-Account-Intelligence-Rules.docx', feature='All rules', asked='Sahaj 10 Sep asked for the rules; sent 10 Sep 11:16 UTC.', answer='Dhruvi 10 Sep: "We\'ll review the rules, guardrails and logic at our end and share our feedback." No feedback received.', date='2026-09-10', status='OPEN', resolves='No.', impact='Every rule in that doc is unapproved; several are now contradicted by client logic.', unclear='Which internal rules the client accepts.', why='Rules absent from the doc read as undisclosed behaviour; rules in it may have to change.', need='Written feedback, or agreement that the later client logic docs supersede it section by section.', sixfile='25_rules_doc_feedback_pending')
q(id='TESTS22', title='Client UI test observations of 22 Sep (tests on current HP 220.docx)', feature='UI', asked='Dhruvi 22 Sep: "I tested the current HP 220 UI and have highlighted a few observations and questions".', answer='Yogesh 22 Sep: "Ok, I\'ll take a look." No written response on record; the document is not on this machine.', date='2026-09-22', status='OPEN', resolves='No.', impact='Unknown until the file is retrieved.', unclear='Contents.', why='Client-raised observations with no recorded disposition.', need='Retrieve the file; answer each observation.', sixfile='26_client_ui_test_observations_22sep')

# ---------- writers ----------
def block(x):
    L=[f"### {x['id']} · {x['title']}", '', f"- **Feature / topic:** {x['feature']}", f"- **Original question:** {x['asked']}", f"- **Original source:** see `00_INDEX/EMAIL_TIMELINE.md`; documents in `05_Questions_and_Clarifications/Source_Documents/`",
       f"- **Client answer:** {x['answer']}", f"- **Date answered:** {x['date']}", f"- **Status:** **{x['status']}**", f"- **Does the answer fully resolve it?** {x['resolves']}", f"- **Implementation impact:** {x['impact']}"]
    if x['sixfile']: L.append(f"- **Unresolved-issue file:** `06_Unresolved_and_Open/{x['sixfile']}.md`")
    return '\n'.join(L)+'\n'
ans=[x for x in Q if x['status'] in ('RESOLVED','PARTIALLY RESOLVED')]
opn=[x for x in Q if x['status'] in ('OPEN','UNRESOLVED')]
hdr='> Status values: RESOLVED = client answer settles it. PARTIALLY RESOLVED = answered, but a delivery, confirmation or sub-question is still outstanding (each has a file in `06_Unresolved_and_Open/`). OPEN = no answer. UNRESOLVED = answered, but the answer does not settle the point.\n> IDs: D1–D43 = the 43 items of 220-Open-Decisions-List.md as numbered in clarifying opens_2.docx; D44–D53 = items added 24 Sep after the list went out; E18-x / E23-x = email Q&A of 18 and 23 Sep; QA16-x = the 16 Sep QA discussion points.\n'
def table(rows):
    T=['| Id | Question | Feature | Status | Answered | Fully resolved? |','|---|---|---|---|---|---|']
    for x in rows: T.append(f"| {x['id']} | {x['title']} | {x['feature']} | {x['status']} | {x['date']} | {x['resolves'][:90]}{'…' if len(x['resolves'])>90 else ''} |")
    return '\n'.join(T)
(OUT/'05_Questions_and_Clarifications/Answered').mkdir(parents=True, exist_ok=True)
(OUT/'05_Questions_and_Clarifications/Open').mkdir(parents=True, exist_ok=True)
(OUT/'05_Questions_and_Clarifications/Answered/ANSWERED_QUESTIONS.md').write_text(f"# Answered questions ({len(ans)})\n\n{hdr}\n## Summary\n\n{table(ans)}\n\n## Detail\n\n"+'\n'.join(block(x) for x in ans))
(OUT/'05_Questions_and_Clarifications/Open/OPEN_QUESTIONS.md').write_text(f"# Open and unresolved questions ({len(opn)})\n\n{hdr}\n## Summary\n\n{table(opn)}\n\n## Detail\n\n"+'\n'.join(block(x) for x in opn))
# 06 files
six={}
for x in Q:
    if x['sixfile']: six.setdefault(x['sixfile'],[]).append(x)
(OUT/'06_Unresolved_and_Open').mkdir(exist_ok=True)
for name,items in six.items():
    x=items[0]
    L=[f"# {x['title']}", '', f"**Issue ids:** {', '.join(i['id'] for i in items)} · **Status:** {' / '.join(sorted(set(i['status'] for i in items)))} · **Affects:** {x['feature']}", '',
       '## Issue', x['title']+'.', '', '## What we asked']
    for i in items: L.append(f"- ({i['id']}) {i['asked']}")
    L+=['', '## What they answered']
    for i in items: L.append(f"- ({i['id']}) {i['answer']}")
    L+=['', '## What is still unclear', x['unclear'] or x['resolves'], '', '## Why it matters', x['why'] or x['impact'], '', '## What we need from the client', x['need'] or '—', '', '## Current status', ' / '.join(sorted(set(i['status'] for i in items)))+f". Last movement: {max(i['date'] for i in items)}. Tracked in `05_Questions_and_Clarifications/Open/OPEN_QUESTIONS.md` and, where already sent, in `07_Internal_Generated/Client_Facing_Round3/`.", '']
    (OUT/'06_Unresolved_and_Open'/f'{name}.md').write_text('\n'.join(L))
idx=['# Unresolved and open issues', '', 'One short file per issue where we asked, the client replied (or promised a delivery), and the point is still not actionable. Purely unasked items (proof-placement defaults F8–F13, 29a–c) live only in `05_Questions_and_Clarifications/Open/`.', '', '| File | Issue | Status | Ids |', '|---|---|---|---|']
for name,items in sorted(six.items()): idx.append(f"| `{name}.md` | {items[0]['title']} | {' / '.join(sorted(set(i['status'] for i in items)))} | {', '.join(i['id'] for i in items)} |")
idx+=['', '## Blocking the 220-account run outright', '- `05_contact_file_missing.md` — five features cannot run for any account.', '- `22_gcp_access.md` — the current environment cannot hold 220 accounts.', '- `01_canonical_account_list.md` — every join.', '', '## Pending deliveries from the client (data, not decisions)', 'Contacts; Name + Country columns on every PredictLeads row; Public Bank Bhd rows; re-crawled Exa dates; job rows for 45 accounts; corrected filings rows (Fletcher, Fonterra, Astra/FIF, United Tractors); Agribank/VPBank filings; the FINAL Rulebook and the three recreated decks (never downloaded here).']
(OUT/'06_Unresolved_and_Open/README.md').write_text('\n'.join(idx)+'\n')
(OUT/'05_Questions_and_Clarifications/README.md').write_text(f"""# Questions and clarifications

- `Answered/ANSWERED_QUESTIONS.md` — {len(ans)} questions with a client answer (RESOLVED or PARTIALLY RESOLVED).
- `Open/OPEN_QUESTIONS.md` — {len(opn)} questions with no answer or an answer that does not settle the point (OPEN or UNRESOLVED).
- `Source_Documents/` — the question and answer documents as exchanged: our 220-Account-Data-Questions-For-Client.md (23 Sep) → client's clarifying opens_1.docx; our 220-Open-Decisions-List.md (24 Sep) → client's clarifying opens_2.docx; our round-3 pack (25 Sep, awaiting answers); the 16 Sep QA documents.
- Every PARTIALLY RESOLVED / UNRESOLVED / blocking-OPEN item has a one-page file in `06_Unresolved_and_Open/`.

Rounds so far:

| Round | Sent | Answered | Vehicle |
|---|---|---|---|
| 0 | 16 Sep (QA discussion points, 12 items) | never | QA-Discussion-Points_2026-09-16.pdf |
| 0 | 18 Sep (4 questions, email) | 18 Sep | email |
| 1 | 23 Sep 18:56 UTC (10 data questions) | 24 Sep 09:30 UTC | clarifying opens_1.docx |
| 1 | 23 Sep 10:36 UTC (4 questions, email) | 23 Sep 12:33 UTC | email |
| 2 | 24 Sep 07:35 UTC (43 decisions) | 24 Sep 14:43 UTC | clarifying opens_2.docx (6 items forwarded to Sahaj) |
| 3 | 25 Sep 02:35 UTC (7 clarifications, 25 open, 2 unresolved) | **pending** | clarifying_opens_3_CLARIFICATIONS.docx, _OPEN_v2.docx, _UNRESOLVED_v2.docx |

Counts by status: RESOLVED {sum(1 for x in Q if x['status']=='RESOLVED')} · PARTIALLY RESOLVED {sum(1 for x in Q if x['status']=='PARTIALLY RESOLVED')} · OPEN {sum(1 for x in Q if x['status']=='OPEN')} · UNRESOLVED {sum(1 for x in Q if x['status']=='UNRESOLVED')} (total {len(Q)}).
""")
print('questions', len(Q), 'answered', len(ans), 'open', len(opn), 'six-files', len(six))
print({s:sum(1 for x in Q if x['status']==s) for s in ('RESOLVED','PARTIALLY RESOLVED','OPEN','UNRESOLVED')})
